/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/computer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.007']} position={[-1.051, 0.2, -1.938]} rotation={[0, Math.PI / 2, 0]} scale={0.069} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.009']} position={[-1.326, 0.199, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.010']} position={[-1.023, 0.199, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.011']} position={[-0.723, 0.199, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.012']} position={[-0.401, 0.199, 1.667]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.013']} position={[-0.08, 0.199, 1.491]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.014']} position={[0.236, 0.211, 2.33]} rotation={[0, Math.PI / 2, 0]} scale={0.095} />
      <mesh geometry={nodes.Text008.geometry} material={materials['Material.015']} position={[-0.405, 0.199, 2.276]} rotation={[0, Math.PI / 2, 0]} scale={0.073} />
      <mesh geometry={nodes.Text009.geometry} material={materials['Material.016']} position={[-0.113, 0.199, 2.276]} rotation={[0, Math.PI / 2, 0]} scale={0.073} />
      <mesh geometry={nodes.Plane.geometry} material={materials.metal} position={[-4.375, 0, 0]} />
      <group position={[-3.647, 2.94, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1.911, 4.248, 3.398]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['metal.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['screen.001']} />
      </group>
      <mesh geometry={nodes.keyboard_base_.geometry} material={materials.metal} position={[-0.595, 0.079, -0.001]} scale={2.427} />
      <mesh geometry={nodes.keys_of_keyboard.geometry} material={materials['Material.001']} position={[-1.383, -0.715, -1.897]} scale={0.141} />
      {/* <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[-3.015, -7.601, 8.055]} scale={25.52} /> */}
    </group>
  )
}

useGLTF.preload('/computer.glb')
