/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/computer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/computer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.007']} position={[0.711, -1.39, -1.938]} rotation={[0, Math.PI / 2, 0]} scale={0.069} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.009']} position={[0.436, -1.391, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.010']} position={[0.739, -1.391, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text004.geometry} material={materials['Material.011']} position={[1.039, -1.391, 2.231]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text005.geometry} material={materials['Material.012']} position={[1.361, -1.391, 1.667]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text006.geometry} material={materials['Material.013']} position={[1.682, -1.391, 1.491]} rotation={[0, Math.PI / 2, 0]} scale={0.1} />
      <mesh geometry={nodes.Text007.geometry} material={materials['Material.014']} position={[1.998, -1.38, 2.33]} rotation={[0, Math.PI / 2, 0]} scale={0.095} />
      <mesh geometry={nodes.Text008.geometry} material={materials['Material.015']} position={[1.357, -1.392, 2.276]} rotation={[0, Math.PI / 2, 0]} scale={0.073} />
      <mesh geometry={nodes.Text009.geometry} material={materials['Material.016']} position={[1.649, -1.392, 2.276]} rotation={[0, Math.PI / 2, 0]} scale={0.073} />
      <mesh geometry={nodes.Plane.geometry} material={materials.metal} position={[-2.613, -1.59, 0]} />
      <group position={[-1.885, 1.349, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1.911, 4.248, 3.398]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['metal.001']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['screen.001']} />
      </group>
      <mesh geometry={nodes.keyboard_base_.geometry} material={materials.metal} position={[1.167, -1.511, -0.001]} scale={2.427} />
      <mesh geometry={nodes.keys_of_keyboard.geometry} material={materials['Material.001']} position={[0.379, -2.306, -1.897]} scale={0.141} />
      {/* <mesh geometry={nodes.Plane002.geometry} material={materials.Material} position={[-3.015, -7.601, 8.055]} scale={25.52} /> */}
    </group>
  )
}

useGLTF.preload('/computer.glb')